strings:
  inputs: 
    - GraffitiBackgrounds/Base.lproj/Localized.strings
  outputs:
    - templateName: structured-swift4
      output: Generated/strings.swift
xcassets:
  inputs:
    - GraffitiBackgrounds/Assets.xcassets
    - GraffitiBackgrounds/Colors.xcassets
  outputs:
    - templateName: swift4
      output: Generated/assets-images.swift
