language: swift
script: xcodebuild CODE_SIGNING_REQUIRED=NO -project GraffitiBackgrounds.xcodeproj -scheme GraffitiBackgrounds -destination platform\=OS\ X,arch\=x86_64 build test | xcpretty
xcode_destination: platform=OS X,arch=x86_64
osx_image: xcode10
addons:
  homebrew:
    packages:
    - swiftlint
    - swiftgen
    - sourcery